Merge of Tropical Sea Level POD
NOAA-GFDL/MDTF-diagnostics pull request #271
Opened 2021-08-26 12:45 UTC by jkrasting

This PR supersedes #107.

**Description**
Include a summary of the change, and link the associated issue (if applicable).  
List any dependencies that are required for this change, including libraries and variables,  
and their metadata (units, frequencies, etc...). Be sure to separate PRs and issues for new PODs and PODs currently under development.

Associated issue # (replace this phrase and parentheses with the issue number)  

**How Has This Been Tested?**
Please describe the tests that you ran to verify your changes in enough detail that  
someone can reproduce them. Include any relevant details for your test configuration  
such as the Python version, package versions, expected POD wallclock time, and the   
operating system(s) you ran your tests on.

**Checklist:**
- [ ] I have reviewed my own code to ensure that if follows the [POD development guidelines](https://mdtf-diagnostics.readthedocs.io/en/latest/sphinx/dev_guidelines.html)
- [ ] My branch is up-to-date with the NOAA-GFDL develop branch, and all merge conflicts are resolved
- [ ] The script are written in Python 3.6 or above (preferred; required if funded by a CPO grant), NCL, or R
- [ ] All of my scripts are in the diagnostics/[POD short name] subdirectory, and include a main_driver script, template html, and settings.jsonc file
- [ ] I have made corresponding changes to the documentation in the POD's doc/ subdirectory
- [ ] If applicable, I've added a .yml file to src/conda, and my environment builds with `conda_env_setup.sh` 
- [ ] I have added any necessary data to input_data/obs_data/[pod short name] and/or input_data/model/[pod short name]
- [ ] My code is portable; it uses [MDTF environment variables](https://mdtf-diagnostics.readthedocs.io/en/latest/sphinx/ref_envvars.html), and does not contain hard-coded file or directory paths
- [ ] I have provided the code to generate digested data files from raw data files
- [ ] Each digested data file generated by the script contains numerical data (no figures), and is 3 GB or less in size
- [ ] The repository contains no extra test scripts or data files

2021-08-29 15:41 UTC, chiaweh2 commented
Hi @jkrasting, Thank you for letting me know about the issue! I will start testing and try to find the problem as soon as possible.

2021-09-06 22:08 UTC, chiaweh2 commented
@jkrasting I was testing the data for a bit and found the synthetic data is only with value over eastern Indian Ocean and part of southern Atlantic Ocean. Do you remember which region you pick to calculate the corresponding value for my POD? I think this might related to the region you picked and if there is value in the synthetic data? I include a figure showing the areacello of your synthetic data below. 
<img width="1025" alt="Screen Shot 2021-09-06 at 4 03 01 PM" src="https://user-images.githubusercontent.com/11950284/132262815-590855ba-5fd3-4cac-9c35-bf704aac933e.png">

2021-09-14 16:57 UTC, jkrasting commented
Hi @chiaweh2 ... When I plot `areacello`, I see data at all locations.  How did you come to find missing data?

This is `CESM2_omip1_r1i1p1f1_gn.areacello.mon.nc` from the synthetic dataset.

![image](https://user-images.githubusercontent.com/6594675/133301168-91552d88-a216-4192-9a18-bd6d86c40362.png)

2021-09-14 19:05 UTC, chiaweh2 commented
Hi @jkrasting  I was using the CESM2_omip1_r1i1p1f1_gn.synthetic.zip file you provided above.

2021-09-14 19:08 UTC, jkrasting commented
@chiaweh2 - could you please post a snippet so I can reproduce your plot?  I am seeing valid values for all longitudes

2021-09-14 19:19 UTC, chiaweh2 commented
@jkrasting Thanks for letting me double check. I think when using panoply (netcdf viewing software) it render the lat Lon wrong which cause the weird plot. I check again by using xarray.plot and shows the same result as your plot. I will see if can find the problem. Sorry for deviate a bit from the original issue.

2021-09-20 15:53 UTC, chiaweh2 commented
@jkrasting I made the changes here on this commit. The problem is the synthetic data is having longitude range of -270-90 which is not the usual OMIP output format I see in original CESM2 which is 0-360. In the new commit I altered the masking array based on 0-360 and mirror it to the corresponding index in -270-90. It seems to solve the problem. Hope this helps! https://github.com/NOAA-GFDL/MDTF-diagnostics/pull/107/commits/953073e77a10cd9296ac7c19dbe97522f3801069

2021-09-28 13:30 UTC, jkrasting commented
@chiaweh2 - looks good, thanks!  I tested this out and it seems to work fine.  My only last remaining request would be to "beef" up the text on the `index.html`.   Could you possibly provide a bit more guidance to model developers on how to interpret these plots and what to look for when reading them? 

@wrongkindofdoctor - we are ready to go with merging this in.

2021-09-28 16:41 UTC, wrongkindofdoctor requested changes

2021-09-28 16:41 UTC, wrongkindofdoctor commented on src/cmip6-cmor-tables/.circleci/config.yml
> +
@jkrasting the cmip6-cmor-tables directory and files should be deleted from the src directory. They were moved to the data folder in a prior commit, and it looks like this change got lost during the rebase.

2021-09-28 16:41 UTC, wrongkindofdoctor commented on src/xr_parser.py
>          coords_list = list(axes_obj.coords)
Remove the changes to xr_parser.py. I believe the fix ended up being addressed elsewhere in PR #185

2021-10-04 15:34 UTC, wrongkindofdoctor commented
@jkrasting I submitted a [PR](https://github.com/jkrasting/MDTF-diagnostics/pull/1) to your branch with the requested changes

2021-10-04 16:59 UTC, jkrasting commented
Thanks @wrongkindofdoctor - I just merged your PR onto my branch.

2021-10-04 17:26 UTC, wrongkindofdoctor approved these changes

2021-10-04 17:27 UTC, merged