Frepp mdtf
NOAA-GFDL/MDTF-diagnostics pull request #351
Opened 2022-05-13 21:17 UTC by aradhakrishnanGFDL

**Description**

GFDL MDTF FREPP wrapper script update, includes a gfdl mdtf frepp template jsonc.

Associated issue #349  

**How Has This Been Tested?**
Yes

**Checklist:**
- [ ] I have reviewed my own code to ensure that if follows the [POD development guidelines](https://mdtf-diagnostics.readthedocs.io/en/latest/sphinx/dev_guidelines.html)
- [ ] My branch is up-to-date with the NOAA-GFDL develop branch, and all merge conflicts are resolved
- [ ] The script are written in Python 3.6 or above (preferred; required if funded by a CPO grant), NCL, or R
- [ ] All of my scripts are in the diagnostics/[POD short name] subdirectory, and include a main_driver script, template html, and settings.jsonc file
- [ ] I have made corresponding changes to the documentation in the POD's doc/ subdirectory
- [ ] If applicable, I've added a .yml file to src/conda, and my environment builds with `conda_env_setup.sh` 
- [ ] I have added any necessary data to input_data/obs_data/[pod short name] and/or input_data/model/[pod short name]
- [ ] My code is portable; it uses [MDTF environment variables](https://mdtf-diagnostics.readthedocs.io/en/latest/sphinx/ref_envvars.html), and does not contain hard-coded file or directory paths
- [ ] I have provided the code to generate digested data files from raw data files
- [ ] Each digested data file generated by the script contains numerical data (no figures), and is 3 GB or less in size
- [ ] The repository contains no extra test scripts or data files

2022-05-24 19:51 UTC, aradhakrishnanGFDL commented
testing notes in #349

2022-05-31 16:41 UTC, ceblanton commented on sites/NOAA_GFDL/mdtf_gfdl.csh
> +if (! -d $in_data_dir) then
missing `endif`

2022-05-31 16:51 UTC, jkrasting requested changes

2022-05-31 16:51 UTC, jkrasting commented on sites/NOAA_GFDL/mdtf_frepp_template.jsonc
> +
```suggestion

// Allow the framework to pull files/variables from multiple components
"any_components": true,

```

2022-05-31 16:51 UTC, jkrasting commented on sites/NOAA_GFDL/mdtf_frepp_template.jsonc
> +
I just came across this JSON option today.  In order for PODs to operate across components, this flag will need to be set.  Might as well set this now.

2022-06-03 14:27 UTC, aradhakrishnanGFDL commented on sites/NOAA_GFDL/mdtf_gfdl.csh
> +set pod_list = '"EOF_500hPa"'
yes per @Wen-hao-Dong's email exchange yesterday

2022-06-03 14:35 UTC, Wen-hao-Dong commented on sites/NOAA_GFDL/mdtf_gfdl.csh
> +set pod_list = '"EOF_500hPa"'
Yes, that is correct. By setting set pod_list = '"EOF_500hPa", "precip_diurnal_cycle"', we get both PODs run successfully.

2022-06-03 16:01 UTC, wrongkindofdoctor commented on sites/NOAA_GFDL/mdtf_gfdl.csh
> +set pod_list = '"EOF_500hPa"'
@Wen-hao-Dong @aradhakrishnanGFDL Thank you!

2022-06-03 16:02 UTC, wrongkindofdoctor approved these changes

2022-06-03 18:33 UTC, merged