Code of conduct
NOAA-GFDL/MDTF-diagnostics pull request #417
Opened 2022-10-20 15:17 UTC by aradhakrishnanGFDL

**Description**

This PR addresses having a code of conduct for the MDTF framework open-source project. It's community facing and provides general ground rules, expectations.

2022-10-20 15:19 UTC, aradhakrishnanGFDL commented
All, this is a preliminary version of the code of conduct. Opening review from all mini-leads members offline before this can be merged in. Expecting to have an initial version merged in before October 2nd.

2022-10-20 17:06 UTC, bitterbark reviewed
Looks good, I made a few small suggestions (sorry I don't see how to edit/suggest text directly!)

2022-10-20 17:06 UTC, bitterbark commented on CODE_OF_CONDUCT.md
> +   * Ask for feedback and listen to them.
Suggest changing this line to: Ask for and listen to feedback

2022-10-20 17:06 UTC, bitterbark commented on CODE_OF_CONDUCT.md
> +   will depend on the work of others. Any decision you take will affect users
suggest: any decision you *make*

2022-10-20 17:06 UTC, bitterbark commented on CODE_OF_CONDUCT.md
> +   technical, happen all the time and this is no exception.
Not sure what "this is no exception" means here.

2022-10-20 17:13 UTC, jkrasting commented
Good idea @aradhakrishnanGFDL.

Maybe a section about "Failure to adhere to this policy will ..." ?

2022-10-20 17:49 UTC, bitterbark requested changes

2022-10-20 17:49 UTC, bitterbark commented on CODE_OF_CONDUCT.md
> +   will depend on the work of others. Any decision you take will affect users
```suggestion
   will depend on the work of others. Any decision you make will affect users
```

2022-10-20 17:49 UTC, bitterbark commented on CODE_OF_CONDUCT.md
> +   * Ask for feedback and listen to them.
```suggestion
   * Ask for and listen to feedback. 
```

2022-10-20 17:53 UTC, aradhakrishnanGFDL commented on CODE_OF_CONDUCT.md
> +   technical, happen all the time and this is no exception.
```suggestion
   technical, happen all the time and this project forum is no exception. 
```

2022-10-20 17:54 UTC, aradhakrishnanGFDL commented on CODE_OF_CONDUCT.md
> +   technical, happen all the time and this is no exception.
```suggestion
   technical, happen all the time and this project community is no exception. 
```

2022-10-20 17:59 UTC, aradhakrishnanGFDL commented
> Good idea @aradhakrishnanGFDL.
> 
> Maybe a section about "Failure to adhere to this policy will ..." ?

 @jkrasting, yes! we need the following section to be complete. This will need more input, just reaching out to entire mini-leads is not the right approach. Usually, few candidate members make a council or steering team (and a mailing list). General reporting guidelines through their respective organizations is okay, but not quite efficient as it spans outside the org. Not sure how to approach it for our work here. Perhaps, Dan can provide pointers here from NOAA CPO perspective- thoughts anyone? 

https://github.com/NOAA-GFDL/MDTF-diagnostics/pull/417/files/8e99517ef539b3245ded38b343e48c5ebcb8abca#diff-ffdbe3a1e7ee93cacfc080b6c635ccf3a8f6b0f00f2fb884f78c6b5f9dac8fd2R87

2022-10-20 17:59 UTC, bitterbark approved these changes

2022-10-21 13:54 UTC, wrongkindofdoctor approved these changes

2023-06-12 18:27 UTC, wrongkindofdoctor reviewed
@aradhakrishnanGFDL Thank you! The Code of Conduct is in great shape. I just a made couple of grammatical suggestions

2023-06-12 18:27 UTC, wrongkindofdoctor commented on CODE_OF_CONDUCT.md
> +Model Diagnostics Task Force framework team is dedicated to providing a respectful and inclusive community for everyone. We provide this code of conduct as part of this commitment, following similar
```suggestion
The Model Diagnostics Task Force framework team is dedicated to providing a respectful and inclusive community for everyone. We provide this code of conduct as part of this commitment, following similar standards for other community development projects, as cited in the references. We do not tolerate harassment or bullying of any community member in any form. This applies equally to all community members regardless of their title, seniority, background, gender, etc., in all forums managed by the MDTF framework team. This includes the mailing lists, our GitHub project space, slack workspaces, in-person events, and any other forums created by the project team. In addition, violations of this code outside these spaces may affect a person's ability to participate within them. As part of the code of conduct policy, we will provide below ground rules for all forums (e.g meetings) created by the project team, supporting project initiatives. 
```

2023-06-12 18:27 UTC, wrongkindofdoctor commented on CODE_OF_CONDUCT.md
> +   * Unwelcome sexual attention, stalking;
```suggestion
   * Unwelcome sexual attention or stalking
```

2023-06-14 17:11 UTC, jkrasting approved these changes

2023-06-14 18:42 UTC, merged