Wheeler-Kiladis and MJO_suite Update code to facilitate re-creating obs
NOAA-GFDL/MDTF-diagnostics pull request #69
Opened 2020-11-20 01:13 UTC by bitterbark

This includes the code changes for both Wheeler-Kiladis (replacing #46) and MJO_suite. I know it isn't ideal to have them together, but #46 got messed up by my attempts to bring my develop branch up to date with upstream/develop. (My understanding from the [developer's instructions](https://mdtf-diagnostics.readthedocs.io/en/latest/sphinx/dev_git_intro.html) is that is not my responsibility after all; please comment if that is incorrect. This code is _not_ updated to upstream/develop.) I would like to commit this as I am able to actually test it. If the destination (bitterbark-develop) is incorrect, please let me know so I can re-create it.

2020-11-20 14:29 UTC, jkrasting requested changes
Looks good, @bitterbark.  Just some minor suggestions to the Python parts.

2020-11-20 14:29 UTC, jkrasting commented on diagnostics/MJO_suite/MJO_suite.py
> +    print("WARNING: MJO_PC_INDEX.nc already exists. Not re-running.")
```suggestion
    warnings.warn("MJO_PC_INDEX.nc already exists. Not re-running.")
```

2020-11-20 14:29 UTC, jkrasting commented on diagnostics/MJO_suite/MJO_suite.py
> +    print("WARNING: MJO_PC_INDEX.nc already exists. Not re-running.")
also add `import warnings` in the header

2020-11-20 14:29 UTC, jkrasting commented on src/data_manager.py
> +            print("\t File not found {}, \n\t program will only fail if this is required and no alternatives found... ".format(path))
Combine this with the exception statement below?

2020-11-20 14:31 UTC, jkrasting commented
There is also a merge conflict with `src/shared_diagnostic.py` 

@wrongkindofdoctor - would you be able to help  @bitterbark with instructions on how to rebase this with the `develop` branch?

2020-11-20 15:44 UTC, wrongkindofdoctor commented
@jkrasting Sure. It looks like NOAA-GFDL: bitterbark-develop will need to be rebased onto develop, and then bitterbark:MJO_suite_update_obs will need to rebased onto NOAA-GFDL: bitterbark-develop.

@jkrasting It is my recommendation that, in the future, POD developers submit PRs to the develop branch for simplicity. In fact, a separate develop branch should not be necessary once we establish a proper release protocol; users should be able to submit PRs directly to main, and checkout whichever stable release they need if they just want to run the code; we can update the documentation with this information, and explain that the main branch in its current state is experimental.

@bitterbark: While the documentation does not explicitly require user branches to be updated with develop, it does recommend updating local forks. I want to establish the protocol for users to update branches and resolve merge conflicts before we merge them into the develop branch. This is both good coding practice, and part of POD maintenance. It also avoids problems on our end of having to resolve large merge conflicts in multiple user branches, particularly during deadlines when multiple PRs are coming in at once.

2020-11-20 16:27 UTC, wrongkindofdoctor commented
@bitterbark Rebasing will pull in any updates from the develop branch, and re-arrange all of your commits so that they are at the "tip" of the branch. I'm not sure about your git expertise, so I'll just use an intro-level step-by-step guide, and you can ignore whatever info you don't need. The instructions will be to rebase onto develop since this will be more straightforward.
Some useful notes:

* if at any point you think you have messed up the rebase, you can always enter `git rebase --abort` to quit the procedure and revert to the original state of bitter-bark:MJO_suite_update_obs
* Rebasing is best done frequently throughout the development process to avoid huge merge conflicts.  You may have to repeat the same edits at multiple points in the rebase process if your branch has not been synced with develop in a long time.
* 3rd party gui tools can be helpful when trying to resolve merge conflicts. One of our developers likes [P4merge](https://www.perforce.com/products/helix-core-apps/merge-diff-tool-p4merge). [Sublime merge](https://www.sublimemerge.com/) also has a free lightweight version.



1) Pull in updates  to the develop branch on your fork using the web interface
2) In your local copy of your MDTF fork on your machine:
  ```
 >  git checkout develop
 >  git fetch
 >  git pull
  ```
3) check out your branch and launch an interactive rebase onto the develop branch
```
>  git checkout bitterbark:MJO_suite_update_obs
>  git rebase -i develop
```
This will open a window in vi/vim (or a different terminal editor if you've set it to something else) with all of your commit hashes ordered with the oldest at the top:
```
pick 52390bj adds feature x
pick nw439s newer commit with edited routine
```
You can combine commits if desired. In the example, changing a `pick` on a newer commit to `squash` combines nw439s with 52390bj
```
pick 52390bj adds feature x
squash nw439s newer commit with edited routine
```
Note that squashing commits is not required by the user, since repo managers have the option to squash commits at merge time. However, it does create a cleaner log.

4) Once you are done with any commit squashing, save your changes and exit the editor (ESC +SHIFT+wq in vim) and the rebase will start. The rebase will stop when it encounters merge conflicts. To see what files need to be fixed, type
```
> git status
```
Files that need fixing will be tagged as having merge conflicts, or with a message that the file has been modified in both branches. 
Then, open each file in an editor, select the changes you want to keep, and save the edited files. When you are finished, run git add on the files with resolved merge conflicts (or remove files that you want to delete if they still exist on one branch)
```
> git add file1
> git add file2
> git rm file3
```
Next, continue the rebase
```
> git rebase --continue
```
A text editor will open listing the commits and resolutions. Exit the editor (vim: ESC+SHIFT+wq) and the rebase will continue

From here, repeat the procedure in 4) for new merge conflicts until the rebase terminates that it is successful.

5) push the rebased branch to the remote copy of your fork using the `--force` option (--force is needed because your local commit history has been modified)
```
> git push -u origin bitterbark:MJO_suite_update_obs --force
```
Your branch should now be up-to-date with develop and free of merge conflicts!

2020-11-20 18:25 UTC, jkrasting commented
This is really good documentation, @wrongkindofdoctor - thanks!

2020-11-20 20:18 UTC, bitterbark commented
@jkrasting  Thanks for the code suggestions. Looks liks some useful tools.

@wrongkindofdoctor, yes, I am new to git and have definitely struggled with the differences between it and tools I have used in the past. 

Re: bitterbark-develop branch:  I can pull request to develop instead; I have no idea why a separate bitterbark-develop branch was made other than that I am so high-maintanance?!! 

Re: updating my code to latest on develop
I am happy to take responsiblity for updating my code with changes that have occured on upstream develop. This is the paradigm I am accustomed to for contributing code, but in carefully following the [developer's instructions](https://mdtf-diagnostics.readthedocs.io/en/latest/sphinx/dev_git_intro.html) it doesn't say to do this, and given the difficulties I am having running the latest version on upstream develop, I thought maybe I could escape the pain. No such luck, so I will return to the struggle. I'd suggest that the process for frequent merges from upstream develop be added to the documentation which is otherwise very helpful.

As for paths forward with this code, I would prefer to avoid the complex world of git rebase, where I would be copy/pasting high-stakes, interactive commands with only the most basic understanding of what I am doing. May I suggest two alternatives:

1) I can start over with the current upstream develop and merge my changes into that, then (once I can test it), create a pull request from there
2) I can revisit pull request #46, in which I had pulled upstream develop to my local copy of my develop branch and pushed those changes to my fork (bitterbark/origin/develop). Assuming that this succeeds at some point, I will then do a separate pull request for the MJO changes which are mostly orthogonal.

The #46 effort failed because of the complications with a changing conda MDTF environment. I will open an issue on that, if okay with you there, because I imagine other developers will have the same problem in the future.

2020-11-20 21:21 UTC, wrongkindofdoctor commented
@bitterbark Yes, you should submit PRs to develop--no need to make things harder on yourself with an intermediate branch :)
Thank you for working to get your branch in sync with develop. I understand the apprehension about rebasing when you are new to git (all of the internet posts warning about the "dangers" of rebasing put me off of it when I first started using git, too). Your proposed solution of starting over using the latest version of develop and re-submitting your PR sounds like it will achieve the same result, though you may still need to resolve merge conflicts. Separating the PRs for the independent changes is also a good strategy.

As for the documentation, I plan on updating it to include clearer language about POD developers' responsibilities to pull in updates often, and submit PRs to develop with fully-updated branches (i.e., with no outstanding merge conflicts). I will also add a section about rebasing with the instructions I provided in this discussion, and will see about hosting a git tutorial for new users if everyone on the team would like.

2021-01-15 07:23 UTC, tsjackson-noaa commented
Hi @bitterbark:
Here's a more detailed report on the problem I've hit in adding the code in this PR to the feature/v3alpha3 branch. I've gotten the code on your branch to work correctly on my machine. (input data is the QBOi.EXP1.AMIP.v1.001 sample data from the model.QBOi.EXP1.AMIP.001.20200818.tar tarball for its full date range, 1975-1981).

<details><summary>MJO_suite log from your branch (successful)</summary><p>

```

 --- MDTF.py calling POD MJO_suite

_CONDA_EXE=/Users/tsj/anaconda2/bin/conda
_CONDA_ROOT=/Users/tsj/anaconda2
Found program python.
Found program ncl.
Found program ncks.
Found contributed.ncl in /Users/tsj/anaconda2/envs/_MDTF_NCL_base/lib/ncarg/nclscripts.
Found gsn_code.ncl in /Users/tsj/anaconda2/envs/_MDTF_NCL_base/lib/ncarg/nclscripts.
Found gsn_csm.ncl in /Users/tsj/anaconda2/envs/_MDTF_NCL_base/lib/ncarg/nclscripts.
Found shea_util.ncl in /Users/tsj/anaconda2/envs/_MDTF_NCL_base/lib/ncarg/nclscripts.
Found diagnostics_cam.ncl in /Users/tsj/anaconda2/envs/_MDTF_NCL_base/lib/ncarg/nclscripts.
	 U,V found on pressure levels (U200,V200)
OBTAINING DAILY OUTPUT
NCL routine /Users/tsj/Documents/climate/MDTF-diagnostics/diagnostics/MJO_suite/daily_netcdf.ncl 
 /Users/tsj/Documents/climate/wkdir/MDTF_QBOi.EXP1.AMIP.v1.001_1975_1981/MJO_suite/model/netCDF/QBOi.EXP1.AMIP.001.pr.day.nc
/Users/tsj/Documents/climate/wkdir/MDTF_QBOi.EXP1.AMIP.v1.001_1975_1981/MJO_suite/model/netCDF/QBOi.EXP1.AMIP.001.u850.day.nc
/Users/tsj/Documents/climate/wkdir/MDTF_QBOi.EXP1.AMIP.v1.001_1975_1981/MJO_suite/model/netCDF/QBOi.EXP1.AMIP.001.v850.day.nc
/Users/tsj/Documents/climate/wkdir/MDTF_QBOi.EXP1.AMIP.v1.001_1975_1981/MJO_suite/model/netCDF/QBOi.EXP1.AMIP.001.u200.day.nc
/Users/tsj/Documents/climate/wkdir/MDTF_QBOi.EXP1.AMIP.v1.001_1975_1981/MJO_suite/model/netCDF/QBOi.EXP1.AMIP.001.v200.day.nc
/Users/tsj/Documents/climate/wkdir/MDTF_QBOi.EXP1.AMIP.v1.001_1975_1981/MJO_suite/model/netCDF/QBOi.EXP1.AMIP.001.rlut.day.nc
 Copyright (C) 1995-2019 - All Rights Reserved
 University Corporation for Atmospheric Research
 NCAR Command Language Version 6.6.2
 The use of this software is governed by a License Agreement.
 See http://www.ncl.ucar.edu/ for more details.
(0)	daily_netcdf.ncl reading /Volumes/Pictures/no_backup/mdtf/inputdata/model/QBOi.EXP1.AMIP.001/day/QBOi.EXP1.AMIP.001.PRECT.day.nc for time coordinates.
(0)	   Assuming without checking that all have same time coordinates!
(0)	Time range indices: 0 1975010100 - 2554 1981123100
(0)	Using date range:
(0)	min=1975010100   max=1981123100
(0)	daily_netcdf.ncl reading /Volumes/Pictures/no_backup/mdtf/inputdata/model/QBOi.EXP1.AMIP.001/day/QBOi.EXP1.AMIP.001.PRECT.day.nc for making precip file!
(0)	Interpolation: Stored lat/lon from pr as desired resolution84 288
(0)	Finished writing file /Users/tsj/Documents/climate/wkdir/MDTF_QBOi.EXP1.AMIP.v1.001_1975_1981/MJO_suite/model/netCDF/QBOi.EXP1.AMIP.001.pr.day.nc
(0)	Lon for var u850 same as stored. NOT interpolating...
(0)	Finished writing file /Users/tsj/Documents/climate/wkdir/MDTF_QBOi.EXP1.AMIP.v1.001_1975_1981/MJO_suite/model/netCDF/QBOi.EXP1.AMIP.001.u850.day.nc
(0)	Lon for var v850 same as stored. NOT interpolating...
(0)	Finished writing file /Users/tsj/Documents/climate/wkdir/MDTF_QBOi.EXP1.AMIP.v1.001_1975_1981/MJO_suite/model/netCDF/QBOi.EXP1.AMIP.001.v850.day.nc
(0)	Lon for var u200 same as stored. NOT interpolating...
(0)	Finished writing file /Users/tsj/Documents/climate/wkdir/MDTF_QBOi.EXP1.AMIP.v1.001_1975_1981/MJO_suite/model/netCDF/QBOi.EXP1.AMIP.001.u200.day.nc
(0)	Lon for var v200 same as stored. NOT interpolating...
(0)	Finished writing file /Users/tsj/Documents/climate/wkdir/MDTF_QBOi.EXP1.AMIP.v1.001_1975_1981/MJO_suite/model/netCDF/QBOi.EXP1.AMIP.001.v200.day.nc
(0)	daily_netcdf.ncl reading /Volumes/Pictures/no_backup/mdtf/inputdata/model/QBOi.EXP1.AMIP.001/day/QBOi.EXP1.AMIP.001.FLUT.day.nc
(0)	Lon for var rlut same as stored. NOT interpolating...
(0)	Finished writing file /Users/tsj/Documents/climate/wkdir/MDTF_QBOi.EXP1.AMIP.v1.001_1975_1981/MJO_suite/model/netCDF/QBOi.EXP1.AMIP.001.rlut.day.nc

COMPUTING DAILY ANOMALIES
NCL routine /Users/tsj/Documents/climate/MDTF-diagnostics/diagnostics/MJO_suite/daily_anom.ncl 
  Copyright (C) 1995-2019 - All Rights Reserved
 University Corporation for Atmospheric Research
 NCAR Command Language Version 6.6.2
 The use of this software is governed by a License Agreement.
 See http://www.ncl.ucar.edu/ for more details.
(0)	daily_anom starting variable pr
(0)	reading /Users/tsj/Documents/climate/wkdir/MDTF_QBOi.EXP1.AMIP.v1.001_1975_1981/MJO_suite/model/netCDF//QBOi.EXP1.AMIP.001.pr.day.nc
(0)	writing /Users/tsj/Documents/climate/wkdir/MDTF_QBOi.EXP1.AMIP.v1.001_1975_1981/MJO_suite/model/netCDF//QBOi.EXP1.AMIP.001.pr.day.anom.nc
(0)	daily_anom starting variable rlut
(0)	reading /Users/tsj/Documents/climate/wkdir/MDTF_QBOi.EXP1.AMIP.v1.001_1975_1981/MJO_suite/model/netCDF//QBOi.EXP1.AMIP.001.rlut.day.nc
(0)	writing /Users/tsj/Documents/climate/wkdir/MDTF_QBOi.EXP1.AMIP.v1.001_1975_1981/MJO_suite/model/netCDF//QBOi.EXP1.AMIP.001.rlut.day.anom.nc
(0)	daily_anom starting variable u200
(0)	reading /Users/tsj/Documents/climate/wkdir/MDTF_QBOi.EXP1.AMIP.v1.001_1975_1981/MJO_suite/model/netCDF//QBOi.EXP1.AMIP.001.u200.day.nc
(0)	writing /Users/tsj/Documents/climate/wkdir/MDTF_QBOi.EXP1.AMIP.v1.001_1975_1981/MJO_suite/model/netCDF//QBOi.EXP1.AMIP.001.u200.day.anom.nc
(0)	daily_anom starting variable u850
(0)	reading /Users/tsj/Documents/climate/wkdir/MDTF_QBOi.EXP1.AMIP.v1.001_1975_1981/MJO_suite/model/netCDF//QBOi.EXP1.AMIP.001.u850.day.nc
(0)	writing /Users/tsj/Documents/climate/wkdir/MDTF_QBOi.EXP1.AMIP.v1.001_1975_1981/MJO_suite/model/netCDF//QBOi.EXP1.AMIP.001.u850.day.anom.nc
(0)	daily_anom starting variable v200
(0)	reading /Users/tsj/Documents/climate/wkdir/MDTF_QBOi.EXP1.AMIP.v1.001_1975_1981/MJO_suite/model/netCDF//QBOi.EXP1.AMIP.001.v200.day.nc
(0)	writing /Users/tsj/Documents/climate/wkdir/MDTF_QBOi.EXP1.AMIP.v1.001_1975_1981/MJO_suite/model/netCDF//QBOi.EXP1.AMIP.001.v200.day.anom.nc
(0)	daily_anom starting variable v850
(0)	reading /Users/tsj/Documents/climate/wkdir/MDTF_QBOi.EXP1.AMIP.v1.001_1975_1981/MJO_suite/model/netCDF//QBOi.EXP1.AMIP.001.v850.day.nc
(0)	writing /Users/tsj/Documents/climate/wkdir/MDTF_QBOi.EXP1.AMIP.v1.001_1975_1981/MJO_suite/model/netCDF//QBOi.EXP1.AMIP.001.v850.day.anom.nc

COMPUTING MJO EOF (may take a while for long time samples)
NCL routine /Users/tsj/Documents/climate/MDTF-diagnostics/diagnostics/MJO_suite/mjo_EOF.ncl 
  Copyright (C) 1995-2019 - All Rights Reserved
 University Corporation for Atmospheric Research
 NCAR Command Language Version 6.6.2
 The use of this software is governed by a License Agreement.
 See http://www.ncl.ucar.edu/ for more details.
(0)	Starting pr
(0)	Computing pr, winter. 2555 time samples, may take a while. Check /Users/tsj/Documents/climate/wkdir/MDTF_QBOi.EXP1.AMIP.v1.001_1975_1981/MJO_suite/model/PS/

Variable: x_season
Type: float
Total Size: 93413376 bytes
            23353344 values
Number of Dimensions: 3
Dimensions and sizes:	[time | 1267] x [lat | 64] x [lon | 288]
Coordinates: 
            time: [   0..2554]
            lat: [-29.68586387434555..29.68586387434556]
            lon: [   0..358.75]
Number Of Attributes: 6
  wgt_runave_op_ncl :	wgt_runave
  Sampling_Sequence :	rad_lwsw
  units :	mm/day
  long_name :	Total (convective and large-scale) precipitation rate (liq + ice)
  cell_methods :	time: mean                                                                                                                                                                                                                                                            
  _FillValue :	9.96921e+36

Variable: x_season_w
Type: double
Total Size: 186826752 bytes
            23353344 values
Number of Dimensions: 3
Dimensions and sizes:	[lat | 64] x [lon | 288] x [time | 1267]
Coordinates: 
            lat: [-29.68586387434555..29.685863874345 [...]

2021-01-18 19:33 UTC, tsjackson-noaa commented
Followup on the [previous comment](https://github.com/NOAA-GFDL/MDTF-diagnostics/issues/69#issuecomment-760705740_): the issue was caused by the use of _FillValue=NaN in data provided to the POD, which is [not supported by NCL](https://www.ncl.ucar.edu/Support/talk_archives/2012/1689.html). In this case, it caused NaNs to be introduced in the output of [wgt_runave_Wrap](https://github.com/bitterbark/MDTF-diagnostics/blob/993dd270c8d1979dba2c3d58155b1beaed3d8f55/diagnostics/MJO_suite/mjo_EOF.ncl#L120), even though neither the input array or the filter had any NaNs or missing values.

No changes are needed to the PR; instead the package doesn't set the _FillValue=NaN attribute if the data will be used for a POD that uses NCL.

2021-02-25 17:47 UTC, closed without merging

2021-02-25 18:04 UTC, tsjackson-noaa commented
Closing this PR since its code has been accepted as part of the [v3.0 beta 3](https://github.com/NOAA-GFDL/MDTF-diagnostics/releases/tag/v3.0-beta.3) release. See PRs NOAA-GFDL/MDTF-diagnostics#147, NOAA-GFDL/MDTF-diagnostics#149.