Update reference on POD settings and env vars
NOAA-GFDL/MDTF-diagnostics pull request #89
Opened 2020-12-07 10:59 UTC by tsjackson-noaa

Refine documentation on the POD's settings file and environment variables, in advance of the telecon. All changes except the first are fully backward-compatible.

- Correct suffix for dimension coordinate env var names from "_dim" to "_coord" [the latter is what the code currently uses; the docs were in error.]
- Add "<dim name>_bnds" env vars for names of coordinate bounds variables.
- Add optional "axis" attribute to dimensions section.
- Emphasize role of varlist path_variable environment variable for finding model data and define a default name for it.
- Wording changes and longer explanations.

2020-12-07 15:35 UTC, wrongkindofdoctor requested changes

2020-12-07 15:35 UTC, wrongkindofdoctor commented on doc/sphinx/ref_envvars.rst
> +    - If ``rename_variables`` is set to ``true`` in the settings file, this will always be equal to <key>. If If ``rename_variables`` is ``false``, this will be whatever the model or data source's na
This line has an extra "if"

2020-12-07 15:35 UTC, wrongkindofdoctor commented on doc/sphinx/ref_settings.rst
> +4. a "time duration": this is a string specifying a time span, used eg. to describe how frequently data is sampled. It consists of an optional integer (if omitted, the integer is assumed to be 1) and
e.g.,

2020-12-07 15:35 UTC, wrongkindofdoctor commented on doc/sphinx/ref_settings.rst
> +6. *arrays*, which are one-dimensional ordered lists delimited with square brackets. Entries can be of any type, eg ``[true, 1, "two"]``.
e.g.,

2020-12-07 15:35 UTC, wrongkindofdoctor commented on doc/sphinx/ref_settings.rst
> +  If ``false``, the framework will ensure all data for a single variable is presented as a single netCDF file. This may lead to large filesizes if your diagnostic uses high-frequency data, in which c
file sizes

2020-12-07 19:09 UTC, tsjackson-noaa commented
Thanks for catching those typos, @wrongkindofdoctor ! Fixed them and also did a proper spell check to make sure there weren't any more.

2020-12-07 19:13 UTC, wrongkindofdoctor submitted a review, later dismissed

2020-12-15 16:19 UTC, jkrasting approved these changes

2020-12-15 16:56 UTC, wrongkindofdoctor approved these changes

2021-01-08 05:15 UTC, merged